apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
spec:
  type: NodePort           # <--- CHANGE 1: Was "ClusterIP"
  ports:
    - port: 80
      targetPort: 8079
      nodePort: 30001      # <--- CHANGE 2: Add this line
  selector:
    name: front-end
